
name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: export GITHUB_BRANCH_NAME=${SHORT_BRANCH_NAME}
      - name: Run a multi-line script
        run: |
          echo Add other actions to "${GITHUB_BRANCH_NAME}",
          echo test, and deploy your project.
